language: php

php:
  - 5.6

# before_install: true

# install: true

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source

script:
  ## PHP_CodeSniffer
  - scripts/bin/phpcs --standard=PSR4 src
  ## PHP Copy/Paste Detector
  - scripts/bin/phpcpd --verbose  src
  ## PHP Mess Detector
  - scripts/bin/phpmd src text cleancode
  - scripts/bin/phpmd src text codesize
  - scripts/bin/phpmd src text controversial
  - scripts/bin/phpmd src text design
  - scripts/bin/phpmd src text naming
  - scripts/bin/phpmd src text unusedcode
  ## PHPLOC
  - scripts/bin/phploc src/Norma
  ## PHPUNIT
  - scripts/bin/phpunit --coverage-clover=coverage.xml
  ## LINT
  - find ./ -type f -name \*.php -exec php -l {} \;

 #  - scripts/bin/run-tests.sh

   # - pear channel-discover pear.phpdoc.org
   # - pear install phpdoc/phpDocumentor

# after_success: true
 # - bash <(curl -s https://codecov.io/bash)
# before_deploy: true

# deploy: true

# after_deploy: true

# after_script: true
