language: php
sudo: required
php:
  - 7

# before_install: true

# install: true

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source
  #- npm install
  #- grunt default
  - chmod u+x src/vendor/bin/phpunit
  - chmod u+x travis/phpmd
  - chmod u+x travis/phpcpd

script:
  ## PHP_CodeSniffer
#  - travis/phpcs --standard=PSR2 src --ignore=*/Requests,*/Helper,*/Router,*/demo/*,*/Adapter/*,php_error.php
  ## PHP Copy/Paste Detector
#  - travis/phpcpd --verbose  src
  ## PHP Mess Detector
#  - travis/phpmd src text cleancode
#  - travis/phpmd src text codesize
#  - travis/phpmd src text controversial
#  - travis/phpmd src text design
#  - travis/phpmd src text naming
#  - travis/phpmd src text unusedcode
  ## PHPLOC
  #- travis/phploc src
  ## PHPUNIT
  - src/vendor/bin/phpunit -v
#  - travis/phpunit --coverage-clover=coverage.xml
  ## LINT
  - find ./src/ -path "./src/vendor" -prune -o -type f -name \*.php -exec php -l {} \;

 #  - travis/run-tests.sh

   # - pear channel-discover pear.phpdoc.org
   # - pear install phpdoc/phpDocumentor

# after_success: true
 # - bash <(curl -s https://codecov.io/bash)
# before_deploy: true

# deploy: true

# after_deploy: true

# after_script: true
