language: php

php:
  - 7

# before_install: true

# install: true

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source
  - apt-get install php-pear
  - pear channel-update pear.php.net
  - pear upgrade-all
  - pear channel-discover pear.phpunit.de
  - pear install -a phpunit/PHPUnit
  - npm install
  - grunt default
  - chmod u+x travis/phpcs
  - chmod u+x travis/phpmd
  - chmod u+x travis/phpcpd
  - chmod u+x travis/phploc
  - chmod u+x travis/phpunit

script:
  ## PHP_CodeSniffer
#  - travis/phpcs --standard=PSR2 src --ignore=*/Requests,*/Helper,*/Router,*/demo/*,*/Adapter/*,php_error.php
  ## PHP Copy/Paste Detector
#  - travis/phpcpd --verbose  src
  ## PHP Mess Detector
#  - travis/phpmd src text cleancode
#  - travis/phpmd src text codesize
#  - travis/phpmd src text controversial
#  - travis/phpmd src text design
#  - travis/phpmd src text naming
#  - travis/phpmd src text unusedcode
  ## PHPLOC
  - travis/phploc src
  ## PHPUNIT
  - phpunit -v
#  - travis/phpunit --coverage-clover=coverage.xml
  ## LINT
  - find ./src/ -type f -name \*.php -exec php -l {} \;

 #  - travis/run-tests.sh

   # - pear channel-discover pear.phpdoc.org
   # - pear install phpdoc/phpDocumentor

# after_success: true
 # - bash <(curl -s https://codecov.io/bash)
# before_deploy: true

# deploy: true

# after_deploy: true

# after_script: true
